from pymilvus import MilvusClient, DataType
from customer_vectorizer import generate_customer_vector

client = MilvusClient(
    "http://localhost:19530")  # Replace with ./milvus_demo.db if you'd like to use Milvus Lite instead

client.drop_collection("customers")

schema = client.create_schema(
    enable_dynamic_field=True
)
schema.add_field(field_name="id", datatype=DataType.INT64, is_primary=True)
schema.add_field(field_name="name", datatype=DataType.VARCHAR, max_length=255)
schema.add_field(field_name="age", datatype=DataType.INT64)
schema.add_field(field_name="interests", datatype=DataType.VARCHAR, max_length=1024)
schema.add_field(field_name="vector", datatype=DataType.FLOAT_VECTOR, dim=32)

index_params = client.prepare_index_params()
index_params.add_index(
    field_name="id",
    index_type="STL_SORT"
)
index_params.add_index(
    field_name="age",
    index_type="STL_SORT"
)
index_params.add_index(
    field_name="vector",
    index_type="IVF_FLAT",
    metric_type="L2",
    params={"nlist": 32}
)

client.create_collection(
    collection_name="customers",
    schema=schema,
    index_params=index_params
)


def prepare_customer_data(id: int, name: str, age: int, interests: list[str]):
    vector = generate_customer_vector(name, age, interests)
    interests_str = ', '.join(interests)
    return {"id": id, "name": name, "age": age, "interests": interests_str, "vector": vector.tolist()}


data = [
    prepare_customer_data(0, "Henry Davis", 72, ['painting', 'fishing']),
    prepare_customer_data(1, "Alice Wilson", 21, ['swimming', 'hiking']),
    prepare_customer_data(2, "Jack Martin", 75, ['painting', 'music', 'running', 'cooking', 'gardening']),
    prepare_customer_data(3, "Pia Thomas", 20, ['music', 'yoga', 'hiking', 'reading', 'cooking']),
    prepare_customer_data(4, "Sam Garcia", 57, ['running', 'writing', 'traveling', 'swimming', 'skiing']),
    prepare_customer_data(5, "Eve Garcia", 77, ['hiking', 'traveling', 'reading']),
    prepare_customer_data(6, "Bob Lopez", 76, ['gardening', 'hiking']),
    prepare_customer_data(7, "Mia Thomas", 45, ['gaming', 'cooking', 'hiking']),
    prepare_customer_data(8, "Oscar Williams", 42, ['hiking', 'running', 'gaming', 'music']),
    prepare_customer_data(9, "Charlie Taylor", 16, ['photography', 'gaming', 'gardening', 'knitting', 'biking']),
    prepare_customer_data(10, "Mia Anderson", 92, ['coding', 'hiking', 'reading', 'gaming', 'writing']),
    prepare_customer_data(11, "Grace Johnson", 39, ['hiking', 'running', 'cooking', 'fishing', 'photography']),
    prepare_customer_data(12, "Bob Jackson", 73, ['coding', 'traveling', 'dancing']),
    prepare_customer_data(13, "Liam Moore", 53, ['swimming', 'biking']),
    prepare_customer_data(14, "Pia Anderson", 85, ['hiking', 'music', 'coding', 'skiing', 'reading']),
    prepare_customer_data(15, "Sam Miller", 16, ['knitting', 'music', 'birdwatching', 'painting']),
    prepare_customer_data(16, "Henry Anderson", 70, ['coding', 'music', 'hiking']),
    prepare_customer_data(17, "Diana Davis", 56, ['yoga', 'painting', 'swimming', 'photography', 'coding']),
    prepare_customer_data(18, "Eve Brown", 62, ['photography', 'running', 'birdwatching']),
    prepare_customer_data(19, "Ivy Garcia", 40, ['birdwatching', 'music', 'painting']),
    prepare_customer_data(20, "Rose Smith", 36, ['dancing', 'fishing']),
    prepare_customer_data(21, "Ivy Martin", 24, ['yoga', 'painting', 'reading', 'cooking']),
    prepare_customer_data(22, "Rose Garcia", 21, ['coding', 'skiing', 'photography']),
    prepare_customer_data(23, "Kara Hernandez", 46, ['birdwatching', 'reading', 'hiking']),
    prepare_customer_data(24, "Henry Williams", 17, ['dancing', 'fishing']),
    prepare_customer_data(25, "Charlie Martinez", 94, ['gardening', 'swimming', 'fishing', 'gaming']),
    prepare_customer_data(26, "Jack Miller", 78, ['gardening', 'music', 'skiing', 'yoga']),
    prepare_customer_data(27, "Eve Lee", 26, ['gaming', 'gardening', 'music', 'yoga', 'writing']),
    prepare_customer_data(28, "Jack Thomas", 87, ['knitting', 'running', 'dancing']),
    prepare_customer_data(29, "Mia Williams", 90, ['yoga', 'coding', 'knitting']),
    prepare_customer_data(30, "Sam Taylor", 45, ['reading', 'fishing', 'writing']),
    prepare_customer_data(31, "Charlie Jackson", 19, ['music', 'hiking', 'birdwatching', 'photography']),
    prepare_customer_data(32, "Nina Gonzalez", 55, ['reading', 'writing', 'hiking']),
    prepare_customer_data(33, "Kara Williams", 50, ['painting', 'reading', 'hiking', 'running']),
    prepare_customer_data(34, "Mia Lee", 19, ['running', 'music', 'knitting', 'biking', 'fishing']),
    prepare_customer_data(35, "Sam Anderson", 23, ['knitting', 'dancing', 'hiking', 'cooking', 'fishing']),
    prepare_customer_data(36, "Mia Lee", 48, ['writing', 'running', 'skiing', 'biking', 'photography']),
    prepare_customer_data(37, "Frank Lopez", 72, ['gaming', 'gardening', 'skiing', 'fishing', 'swimming']),
    prepare_customer_data(38, "Quinn Wilson", 29, ['photography', 'biking', 'reading', 'coding', 'fishing']),
    prepare_customer_data(39, "Nina Thomas", 34, ['gaming', 'reading', 'fishing']),
    prepare_customer_data(40, "Henry Lopez", 77, ['dancing', 'gardening', 'fishing', 'gaming']),
    prepare_customer_data(41, "Diana Johnson", 57, ['coding', 'reading', 'swimming']),
    prepare_customer_data(42, "Kara Lee", 35, ['photography', 'music', 'gardening', 'birdwatching', 'cooking']),
    prepare_customer_data(43, "Henry Smith", 59, ['skiing', 'biking', 'gardening', 'coding']),
    prepare_customer_data(44, "Henry Hernandez", 49, ['gaming', 'dancing', 'music', 'swimming', 'skiing']),
    prepare_customer_data(45, "Sam Gonzalez", 57, ['coding', 'reading', 'fishing', 'dancing']),
    prepare_customer_data(46, "Sam Lopez", 70, ['reading', 'skiing']),
    prepare_customer_data(47, "Frank Jackson", 57, ['gaming', 'cooking', 'swimming']),
    prepare_customer_data(48, "Rose Anderson", 29, ['photography', 'yoga', 'biking', 'swimming']),
    prepare_customer_data(49, "Diana Lopez", 32, ['fishing', 'traveling']),
    prepare_customer_data(50, "Ivy Moore", 62, ['gardening', 'knitting', 'writing']),
    prepare_customer_data(51, "Oscar Brown", 68, ['hiking', 'yoga', 'birdwatching']),
    prepare_customer_data(52, "Eve Gonzalez", 28, ['knitting', 'traveling', 'biking']),
    prepare_customer_data(53, "Liam Wilson", 25, ['painting', 'running', 'coding']),
    prepare_customer_data(54, "Rose Davis", 84, ['photography', 'swimming', 'music']),
    prepare_customer_data(55, "Nina Jackson", 47, ['fishing', 'reading', 'yoga']),
    prepare_customer_data(56, "Charlie Taylor", 58, ['writing', 'traveling', 'birdwatching']),
    prepare_customer_data(57, "Grace Miller", 33, ['swimming', 'knitting', 'gardening']),
    prepare_customer_data(58, "Pia Garcia", 44, ['gaming', 'skiing', 'photography']),
    prepare_customer_data(59, "Diana Hernandez", 91, ['reading', 'hiking']),
    prepare_customer_data(60, "Quinn Anderson", 38, ['biking', 'gardening', 'skiing', 'writing']),
    prepare_customer_data(61, "Rose Taylor", 63, ['traveling', 'photography']),
    prepare_customer_data(62, "Oscar Johnson", 82, ['skiing', 'writing', 'hiking', 'fishing']),
    prepare_customer_data(63, "Eve Gonzalez", 34, ['reading', 'music']),
    prepare_customer_data(64, "Sam Jackson", 28, ['yoga', 'photography', 'biking']),
    prepare_customer_data(65, "Bob Moore", 48, ['traveling', 'dancing']),
    prepare_customer_data(66, "Diana Brown", 53, ['swimming', 'birdwatching', 'reading']),
    prepare_customer_data(67, "Quinn Smith", 37, ['fishing', 'knitting']),
    prepare_customer_data(68, "Mia Hernandez", 64, ['hiking', 'skiing', 'yoga']),
    prepare_customer_data(69, "Henry Gonzalez", 49, ['reading', 'painting']),
    prepare_customer_data(70, "Sam Taylor", 55, ['biking', 'gaming']),
    prepare_customer_data(71, "Liam Brown", 72, ['fishing', 'knitting', 'traveling']),
    prepare_customer_data(72, "Eve Davis", 61, ['writing', 'gaming', 'photography']),
    prepare_customer_data(73, "Charlie Johnson", 36, ['traveling', 'reading', 'birdwatching']),
    prepare_customer_data(74, "Bob Jackson Jr.", 22, ['swimming', 'biking', 'gardening']),
    prepare_customer_data(75, "Henry Garcia", 41, ['hiking', 'yoga']),
    prepare_customer_data(76, "Rose Moore", 60, ['skiing', 'gardening']),
    prepare_customer_data(77, "Ivy Hernandez", 35, ['traveling', 'knitting', 'photography']),
    prepare_customer_data(78, "Frank Lee", 42, ['gaming', 'reading']),
    prepare_customer_data(79, "Oscar Taylor", 74, ['skiing', 'dancing', 'yoga']),
    prepare_customer_data(80, "Mia Gonzalez", 31, ['painting', 'hiking']),
    prepare_customer_data(81, "Diana Smith", 58, ['reading', 'cooking']),
    prepare_customer_data(82, "Eve Anderson", 77, ['birdwatching', 'knitting']),
    prepare_customer_data(83, "Charlie Lopez", 39, ['yoga', 'photography']),
    prepare_customer_data(84, "Grace Moore", 67, ['painting', 'fishing']),
    prepare_customer_data(85, "Henry Williams", 30, ['gardening', 'skiing']),
    prepare_customer_data(86, "Bob Taylor", 51, ['yoga', 'writing']),
    prepare_customer_data(87, "Quinn Gonzalez", 59, ['reading', 'gardening']),
    prepare_customer_data(88, "Ivy Lee", 48, ['traveling', 'dancing', 'skiing']),
    prepare_customer_data(89, "Nina Hernandez", 26, ['swimming', 'birdwatching']),
    prepare_customer_data(90, "Mia Davis", 45, ['gaming', 'photography']),
    prepare_customer_data(91, "Frank Johnson", 62, ['skiing', 'knitting']),
    prepare_customer_data(92, "Liam Smith", 29, ['dancing', 'biking']),
    prepare_customer_data(93, "Rose Gonzalez", 80, ['birdwatching', 'hiking']),
    prepare_customer_data(94, "Oscar Jackson", 49, ['painting', 'traveling']),
    prepare_customer_data(95, "Nina Brown", 19, ['cooking', 'swimming']),
    prepare_customer_data(96, "Ivy Moore", 33, ['photography', 'yoga', 'skiing']),
    prepare_customer_data(97, "Henry Davis", 43, ['biking', 'gaming']),
    prepare_customer_data(98, "Diana Johnson", 57, ['gardening', 'fishing']),
    prepare_customer_data(99, "Charlie Gonzalez", 66, ['traveling', 'birdwatching']),
    prepare_customer_data(100, "Mia Taylor", 25, ['yoga', 'writing']),
    prepare_customer_data(101, "Eve Lee", 40, ['hiking', 'swimming']),
    prepare_customer_data(102, "Oscar Brown", 73, ['birdwatching', 'skiing']),
    prepare_customer_data(103, "Nina Davis", 29, ['painting', 'dancing']),
    prepare_customer_data(104, "Frank Johnson", 52, ['writing', 'traveling']),
    prepare_customer_data(105, "Grace Taylor", 61, ['yoga', 'gardening']),
    prepare_customer_data(106, "Sam Hernandez", 38, ['biking', 'photography']),
    prepare_customer_data(107, "Quinn Gonzalez", 46, ['knitting', 'cooking']),
    prepare_customer_data(108, "Mia Anderson", 78, ['birdwatching', 'reading']),
    prepare_customer_data(109, "Henry Lopez", 35, ['skiing', 'hiking']),
    prepare_customer_data(110, "Diana Williams", 44, ['gardening', 'traveling']),
    prepare_customer_data(111, "Rose Smith", 67, ['swimming', 'dancing']),
    prepare_customer_data(112, "Oscar Davis", 50, ['writing', 'painting']),
    prepare_customer_data(113, "Charlie Taylor", 42, ['hiking', 'photography']),
    prepare_customer_data(114, "Eve Gonzalez", 64, ['yoga', 'cooking']),
    prepare_customer_data(115, "Liam Moore", 33, ['traveling', 'reading']),
    prepare_customer_data(116, "Ivy Hernandez", 56, ['biking', 'skiing']),
    prepare_customer_data(117, "Grace Brown", 60, ['knitting', 'gardening']),
    prepare_customer_data(118, "Sam Jackson", 25, ['birdwatching', 'gaming']),
    prepare_customer_data(119, "Mia Johnson", 48, ['dancing', 'writing']),
    prepare_customer_data(120, "Frank Lopez", 39, ['fishing', 'traveling']),
    prepare_customer_data(121, "Diana Gonzalez", 72, ['photography', 'hiking']),
    prepare_customer_data(122, "Henry Davis", 54, ['reading', 'yoga']),
    prepare_customer_data(123, "Bob Williams", 41, ['biking', 'cooking']),
    prepare_customer_data(124, "Charlie Taylor", 65, ['skiing', 'painting']),
    prepare_customer_data(125, "Oscar Smith", 32, ['gardening', 'swimming']),
    prepare_customer_data(126, "Grace Jackson", 59, ['birdwatching', 'writing']),
    prepare_customer_data(127, "Nina Lopez", 45, ['hiking', 'knitting']),
    prepare_customer_data(128, "Ivy Brown", 27, ['traveling', 'fishing']),
    prepare_customer_data(129, "Frank Johnson", 62, ['yoga', 'reading']),
    prepare_customer_data(130, "Rose Gonzalez", 31, ['cooking', 'photography']),
    prepare_customer_data(131, "Sam Taylor", 70, ['skiing', 'biking']),
    prepare_customer_data(132, "Eve Moore", 49, ['dancing', 'gardening']),
    prepare_customer_data(133, "Quinn Davis", 37, ['birdwatching', 'painting']),
    prepare_customer_data(134, "Mia Smith", 26, ['writing', 'traveling']),
    prepare_customer_data(135, "Diana Jackson", 66, ['hiking', 'swimming']),
    prepare_customer_data(136, "Oscar Hernandez", 43, ['reading', 'cooking']),
    prepare_customer_data(137, "Grace Lopez", 52, ['skiing', 'photography']),
    prepare_customer_data(138, "Charlie Brown", 36, ['biking', 'dancing']),
    prepare_customer_data(139, "Henry Taylor", 58, ['fishing', 'writing']),
    prepare_customer_data(140, "Nina Gonzalez", 74, ['gardening', 'yoga']),
    prepare_customer_data(141, "Frank Anderson", 29, ['birdwatching', 'traveling']),
    prepare_customer_data(142, "Liam Davis", 47, ['hiking', 'knitting']),
    prepare_customer_data(143, "Rose Smith", 34, ['photography', 'skiing']),
    prepare_customer_data(144, "Diana Lopez", 63, ['cooking', 'swimming']),
    prepare_customer_data(145, "Grace Brown", 42, ['painting', 'writing', 'coding']),
    prepare_customer_data(146, "Oscar Williams", 55, ['biking', 'dancing']),
    prepare_customer_data(147, "Ivy Gonzalez", 40, ['reading', 'gardening']),
    prepare_customer_data(148, "Sam Taylor", 68, ['birdwatching', 'hiking']),
    prepare_customer_data(149, "Henry Moore", 31, ['photography', 'traveling']),
    prepare_customer_data(150, "Eve Davis", 53, ['knitting', 'yoga']),
    prepare_customer_data(151, "Liam Johnson", 48, ['fishing', 'reading']),
    prepare_customer_data(152, "Rose Taylor", 67, ['cooking', 'traveling']),
    prepare_customer_data(153, "Quinn Lopez", 29, ['dancing', 'writing']),
    prepare_customer_data(154, "Frank Gonzalez", 54, ['skiing', 'biking']),
    prepare_customer_data(155, "Oscar Brown", 33, ['birdwatching', 'gardening']),
    prepare_customer_data(156, "Mia Davis", 59, ['knitting', 'hiking']),
    prepare_customer_data(157, "Grace Hernandez", 45, ['photography', 'swimming']),
    prepare_customer_data(158, "Eve Smith", 73, ['traveling', 'painting']),
    prepare_customer_data(159, "Sam Johnson", 37, ['reading', 'yoga']),
    prepare_customer_data(160, "Diana Williams", 50, ['biking', 'dancing']),
    prepare_customer_data(161, "Henry Gonzalez", 64, ['skiing', 'writing']),
    prepare_customer_data(162, "Ivy Moore", 31, ['gardening', 'birdwatching']),
    prepare_customer_data(163, "Rose Taylor", 42, ['hiking', 'fishing']),
    prepare_customer_data(164, "Grace Jackson", 76, ['cooking', 'knitting']),
    prepare_customer_data(165, "Oscar Davis", 46, ['traveling', 'photography']),
    prepare_customer_data(166, "Mia Lopez", 28, ['painting', 'skiing']),
    prepare_customer_data(167, "Charlie Brown", 60, ['swimming', 'yoga']),
    prepare_customer_data(168, "Eve Smith", 34, ['writing', 'biking']),
    prepare_customer_data(169, "Liam Gonzalez", 39, ['gardening', 'hiking']),
    prepare_customer_data(170, "Frank Taylor", 71, ['reading', 'dancing']),
    prepare_customer_data(171, "Sam Johnson", 55, ['knitting', 'birdwatching']),
    prepare_customer_data(172, "Grace Lopez", 40, ['fishing', 'traveling']),
    prepare_customer_data(173, "Diana Brown", 33, ['cooking', 'photography']),
    prepare_customer_data(174, "Nina Moore", 62, ['skiing', 'writing']),
    prepare_customer_data(175, "Oscar Smith", 47, ['yoga', 'hiking']),
    prepare_customer_data(176, "Quinn Davis", 29, ['swimming', 'painting']),
    prepare_customer_data(177, "Rose Jackson", 53, ['biking', 'reading']),
    prepare_customer_data(178, "Henry Gonzalez", 66, ['traveling', 'gardening']),
    prepare_customer_data(179, "Mia Johnson", 44, ['photography', 'dancing']),
    prepare_customer_data(180, "Charlie Taylor", 74, ['birdwatching', 'knitting']),
    prepare_customer_data(181, "Grace Williams", 36, ['hiking', 'fishing']),
    prepare_customer_data(182, "Sam Moore", 58, ['cooking', 'skiing']),
    prepare_customer_data(183, "Frank Hernandez", 41, ['swimming', 'writing']),
    prepare_customer_data(184, "Eve Davis", 69, ['reading', 'gardening']),
    prepare_customer_data(185, "Oscar Lopez", 32, ['yoga', 'traveling']),
    prepare_customer_data(186, "Mia Gonzalez", 49, ['painting', 'biking']),
    prepare_customer_data(187, "Henry Brown", 27, ['dancing', 'birdwatching']),
    prepare_customer_data(188, "Rose Smith", 61, ['knitting', 'skiing']),
    prepare_customer_data(189, "Liam Jackson", 38, ['photography', 'hiking']),
    prepare_customer_data(190, "Diana Taylor", 75, ['fishing', 'writing']),
    prepare_customer_data(191, "Quinn Moore", 35, ['cooking', 'reading']),
    prepare_customer_data(192, "Charlie Davis", 50, ['swimming', 'yoga']),
    prepare_customer_data(193, "Grace Hernandez", 43, ['biking', 'traveling']),
    prepare_customer_data(194, "Eve Williams", 68, ['gardening', 'painting']),
    prepare_customer_data(195, "Oscar Smith", 30, ['birdwatching', 'dancing']),
    prepare_customer_data(196, "Sam Lopez", 57, ['hiking', 'skiing']),
    prepare_customer_data(197, "Nina Brown", 41, ['writing', 'photography']),
    prepare_customer_data(198, "Frank Taylor", 63, ['knitting', 'cooking']),
    prepare_customer_data(199, "Mia Gonzalez", 28, ['reading', 'swimming']),
]

res = client.insert(
    collection_name="customers",
    data=data
)
print(res)

print("SUCCESSFUL")
